### ISSUE TITLE
Matrix.column_count returns nil after require 'daru'

### ISSUE THREAD

**Issue by tramuntanal** [SciRuby/daru#393] opened 2017-08-24 21:18 UTC
The bug appears in two forms.
1. If the Matrix was created before requiring 'daru' `colum_size` doesn't work:
```
irb(main):002:0> require 'matrix'
=> true
irb(main):003:0> m= Matrix.zero(2)
=> Matrix[[0, 0], [0, 0]]
irb(main):004:0> m.column_count
=> 2
irb(main):005:0> m.column_size
=> 2
irb(main):006:0> require 'daru'
=> true
irb(main):007:0> m.column_count
=> 2
irb(main):008:0> m.column_size
=> nil
```

2. If the Matrix is created after requiring 'daru' `colum_count` doesn't work:
```
irb(main):001:0> require 'matrix'
=> true
irb(main):002:0> m= Matrix.zero(2)
=> Matrix[[0, 0], [0, 0]]
irb(main):003:0> m.column_count
=> 2
irb(main):004:0> m.column_size
=> 2
irb(main):005:0> require 'daru'
=> true
irb(main):006:0> m= Matrix.zero(2)
=> Matrix[[0, 0], [0, 0]]
irb(main):007:0> m.column_count
=> nil
irb(main):008:0> m.column_size
=> 2
```

I can't find any reference to `#column_count` or `#column_size` in the Daru code.

**Comment by zverok** [comment] 2017-08-25 11:07
Aknowledged. It is nasty bag, caused by [backports](https://github.com/marcandre/backports) gem requireing. Unfortunately, it is not that easy to fix: backports required not only in daru itself, but also in `packable` gem, required by `nmatrix`. I've did a [PR](https://github.com/marcandre/packable/pull/9) to packable, but I am not sure when it could be merged :( Only after that we can proceed with fixing the bug.

**Comment by v0dro** [comment] 2017-08-27 09:27
Issue has been solved by removing backports dependency.

**Comment by zverok** [comment] 2017-08-27 09:49
Ugh. We can't mark this issue as a resolved. I should've mark corresponding PR as WIP, sorry :(
The problem describe in this comment: 

> It is nasty bag, caused by backports gem requireing. Unfortunately, it is not that easy to fix: backports required not only in daru itself, but also in packable gem, required by nmatrix. I've did a PR to packable, but I am not sure when it could be merged :( Only after that we can proceed with fixing the bug.

I provided a PR to original `packable` repo, and it was merged, but only after that I've noticed that SciRuby have taken over packable.

So, the course of actions are:
* update `packable` gem according to https://github.com/marcandre/packable/pull/9
* release it;
* update Daru to use the new version;
* ...then, make Daru require only part of backports (as we are supporting Ruby 2.0, we still need it, just instead of `require 'backports'` we should use something like `require 'backports/2.1/hash/to_h'` or something)

**Comment by v0dro** [comment] 2017-08-27 17:16
If you can submit that PR to sciruby/packable I can merge it and release a new version.

**Comment by zverok** [comment] 2017-08-27 19:39
Done the PR to SciRuby/packable.

**Comment by zverok** [comment] 2018-07-01 17:31
It is fixed in master, I'll release a new minor version soon.

**Closed by zverok** 2018-07-01 17:31 UTC
Labels: bug: major
